// ============================================
// ITALIAN BRAINROT - KARAKTER DATABASE
// Ryddet op med korrekte billede-mappinger
// ============================================

const CHARACTERS = [
    // === HOVEDKARAKTERER ===
    { name: 'TRALALERO TRALALA', emoji: '🦈', description: 'Den originale haj med ben', image: 'images/tralalero-tralala.jpg.jpeg', color: '#1e90ff', rarity: '⭐⭐⭐⭐⭐' },
    { name: 'TUNG TUNG TUNG SAHUR', emoji: '🗿', description: 'Mystisk statue-væsen', image: 'images/tung-tung-hurar-tung-tung-tung-sahur.jpg.jpeg', color: '#8b4513', rarity: '⭐⭐⭐⭐⭐' },
    { name: 'BALLERINA CAPPUCCINA', emoji: '☕', description: 'Dansende kaffekop', image: 'images/ballerina-cappucina.jpg.jpeg', color: '#d2691e', rarity: '⭐⭐⭐⭐' },
    { name: 'BRR BRR PATAPIM', emoji: '🥶', description: 'Kold lille skabning', image: 'images/brr-brr-patapim.jpg.jpeg', color: '#00bfff', rarity: '⭐⭐⭐⭐⭐' },
    { name: 'BOMBARDIRO CROCODILO', emoji: '🐊', description: 'Fly-krokodille hybrid', image: 'images/bombardiro-crocodilo.jpg.jpeg', color: '#228b22', rarity: '⭐⭐⭐⭐⭐' },
    { name: 'CAPPUCCINO ASSASSINO', emoji: '☠️', description: 'Farlig kaffedræber', image: 'images/cappuccino-assassino.jpg.jpeg', color: '#8b0000', rarity: '⭐⭐⭐⭐' },
    { name: 'LIRILI LARILA', emoji: '🐘', description: 'Musikalsk elefant', image: 'images/lirili-larila.jpg.jpeg', color: '#9370db', rarity: '⭐⭐⭐⭐' },
    { name: 'TRIPPI TROPPI', emoji: '🍄', description: 'Trippy svampevæsen', image: 'images/trippi-troppi-troppa-trippa.jpg.jpeg', color: '#ff69b4', rarity: '⭐⭐⭐⭐' },
    { name: 'CHIMPANZINI BANANINI', emoji: '🐵', description: 'Banan-elskende abe', image: 'images/chimpanzini-bananini.jpg.jpeg', color: '#ffd700', rarity: '⭐⭐⭐' },
    { name: 'BONECA AMBALABU', emoji: '🎎', description: 'Mystisk dukke', image: 'images/boneca-ambalabu.jpg.jpeg', color: '#ff1493', rarity: '⭐⭐⭐⭐' },
    { name: 'BOMBOMBINI GUSINI', emoji: '💣', description: 'Eksplosiv gås', image: 'images/bombombini-gusini.jpg.jpeg', color: '#ff4500', rarity: '⭐⭐⭐' },
    { name: 'BOBRITO BANDITO', emoji: '🦫', description: 'Bandit-bæver', image: 'images/bobrito-bandito.jpg.jpeg', color: '#8b4513', rarity: '⭐⭐⭐⭐' },
    { name: 'FRIGO CAMELO', emoji: '🐪', description: 'Køleskabs-kamel', image: 'images/frigo-camelo.jpg.jpeg', color: '#daa520', rarity: '⭐⭐⭐' },
    { name: 'LA VACA SATURNO SATURNITA', emoji: '🐄', description: 'Saturn-ko fra rummet', image: 'images/la-vaca-saturno-saturnita.jpg.jpeg', color: '#9932cc', rarity: '⭐⭐⭐⭐' },
    { name: 'TRULIMERO TRULICINA', emoji: '🎭', description: 'Dobbelt-personlighed', image: 'images/trulimero-trulicina.jpg.jpeg', color: '#ff6347', rarity: '⭐⭐⭐' },
    { name: 'BURBALONI LULILOLI', emoji: '🫧', description: 'Boble-væsen', image: 'images/burbaloni-lulilolli.jpg.jpeg', color: '#87ceeb', rarity: '⭐⭐⭐' },
    { name: 'GLORBO FRUTTODRILLO', emoji: '🍇', description: 'Frugt-gorilla', image: 'images/glorbo-fruttodrillo.jpg.jpeg', color: '#9400d3', rarity: '⭐⭐⭐' },
    { name: 'FRULLI FRULLA', emoji: '🌪️', description: 'Tornado af frugt', image: 'images/frulli-frulla.jpg.jpeg', color: '#ff6347', rarity: '⭐⭐⭐' },
    { name: 'RHINO TOASTERINO', emoji: '🦏', description: 'Brødrister-næsehorn', image: 'images/rhino-toasterino.jpg.jpeg', color: '#708090', rarity: '⭐⭐⭐' },
    { name: 'ORANGUTINI ANANASINI', emoji: '🦧', description: 'Ananas-orangutang', image: 'images/orangutini-ananasini.jpg.jpeg', color: '#ff8c00', rarity: '⭐⭐⭐' },
    
    // === SAHUR FAMILIEN ===
    { name: 'JOB JOB JOB SAHUR', emoji: '💼', description: 'Arbejdende sahur', image: 'images/job-job-job-sahur.webp', color: '#4169e1', rarity: '⭐⭐' },
    { name: 'TA TA TA SAHUR', emoji: '🥁', description: 'Tromme-sahur', image: 'images/ta-ta-ta-ta-ta-ta-ta-ta-ta-ta-ta-sahur.jpg.jpeg', color: '#ff4500', rarity: '⭐⭐' },
    { name: 'TE TE TE SAHUR', emoji: '🍵', description: 'Te-sahur', image: 'images/te-te-te-sahur.webp', color: '#228b22', rarity: '⭐⭐' },
    { name: 'TO TO TO SAHUR', emoji: '🚂', description: 'Tog-sahur', image: 'images/to-to-to-sahur.png', color: '#4682b4', rarity: '⭐⭐' },
    { name: 'MOTOSAHUR', emoji: '🏍️', description: 'Motorcykel-sahur', image: 'images/91_motosahur.jpg', color: '#dc143c', rarity: '⭐⭐⭐' },
    
    // === DYRE-FRUGT HYBRIDER ===
    { name: 'TIGROLIGRE FRUTONNI', emoji: '🐯', description: 'Tiger-frugt hybrid', image: 'images/tigroligre-frutonni.jpg.jpeg', color: '#ff8c00', rarity: '⭐⭐⭐' },
    { name: 'TIGRRULLINI WATERMELLINI', emoji: '🍉', description: 'Vandmelon-tiger', image: 'images/tigrrullini-watermellini.jpg.jpeg', color: '#ff6b6b', rarity: '⭐⭐⭐' },
    { name: 'GORILLO WATERMELLONDRILLO', emoji: '🦍', description: 'Vandmelon-gorilla', image: 'images/gorillo-watermellondrillo.jpg.jpeg', color: '#32cd32', rarity: '⭐⭐⭐' },
    { name: 'BANANITA DOLFINITA', emoji: '🐬', description: 'Banan-delfin', image: 'images/bananita-dolfinita.jpg.jpeg', color: '#ffd700', rarity: '⭐⭐⭐' },
    { name: 'PANDACCINI BANANINI', emoji: '🐼', description: 'Banan-panda', image: 'images/pandaccini-bananini.jpg.jpeg', color: '#000000', rarity: '⭐⭐⭐' },
    { name: 'BLUEBERRINNI OCTOPUSSINI', emoji: '🐙', description: 'Blåbær-blæksprutte', image: 'images/blueberrinni-octopussini.jpg.jpeg', color: '#4169e1', rarity: '⭐⭐⭐' },
    { name: 'CAPYBARELLI BANANALELLI', emoji: '🦫', description: 'Banan-capybara', image: 'images/capybarelli-bananalelli.jpg.jpeg', color: '#8b4513', rarity: '⭐⭐⭐' },
    { name: 'COCOFANTO ELEFANTO', emoji: '🥥', description: 'Kokosnød-elefant', image: 'images/cocofanto-elefanto.jpg.jpeg', color: '#8b4513', rarity: '⭐⭐⭐' },
    { name: 'AVOCADINI ANTILOPINI', emoji: '🥑', description: 'Avocado-antilope', image: 'images/avocadini-antilopini.jpg.jpeg', color: '#9acd32', rarity: '⭐⭐⭐' },
    { name: 'GRAIPUSSI MEDUSSI', emoji: '🍇', description: 'Drue-vandmand', image: 'images/graipussi-medussi.jpg.jpeg', color: '#9400d3', rarity: '⭐⭐⭐' },
    { name: 'FLAMINGULLI GULLI GULLI', emoji: '🦩', description: 'Dansende flamingo', image: 'images/flamingulli-gulli-gulli.jpg.jpeg', color: '#ff69b4', rarity: '⭐⭐⭐' },
    { name: 'TORRTUGINNI DRAGONFRUTINNI', emoji: '🐢', description: 'Dragefrugt-skildpadde', image: 'images/torrtuginni-dragonfrutinni.jpg.jpeg', color: '#ff1493', rarity: '⭐⭐⭐' },
    { name: 'ELEPHANTUCHI BANANUCHI', emoji: '🐘', description: 'Banan-elefant', image: 'images/elephantuchi-bananuchi.jpg.jpeg', color: '#808080', rarity: '⭐⭐⭐' },
    { name: 'PEROCHELLO LEMONCHELLO', emoji: '🦜', description: 'Citron-papegøje', image: 'images/69_perochello_lemonchello.jpg', color: '#ffd700', rarity: '⭐⭐⭐' },
    { name: 'RACCOONI WATERMELUNNI', emoji: '🦝', description: 'Vandmelon-vaskebjørn', image: 'images/88_raccooni_watermelunni.jpg', color: '#708090', rarity: '⭐⭐⭐' },
    
    // === SPECIELLE KARAKTERER ===
    { name: 'SIGMA BOY', emoji: '😎', description: 'Den ultimative sigma', image: 'images/sigma-boy.jpg.jpeg', color: '#000000', rarity: '⭐⭐⭐⭐⭐' },
    { name: 'CHAI MAESTRO', emoji: '🍵', description: 'Te-mester', image: 'images/chai-maestro.jpg.jpeg', color: '#d2691e', rarity: '⭐⭐⭐⭐' },
    { name: 'DINOSAHURUS', emoji: '🦖', description: 'Dinosaur-sahur', image: 'images/dinosahurus.webp', color: '#228b22', rarity: '⭐⭐⭐⭐' },
    { name: 'POT HOTSPOT', emoji: '📶', description: 'WiFi-potte', image: 'images/pot-hotspot.jpg.jpeg', color: '#4169e1', rarity: '⭐⭐⭐' },
    { name: 'GANGSTER FOOTERA', emoji: '👟', description: 'Gangster-fod', image: 'images/gangster-footera.webp', color: '#000000', rarity: '⭐⭐⭐' },
    { name: 'CHEF CRABRACADABRA', emoji: '🦀', description: 'Magisk kok-krabbe', image: 'images/chef-crabracadabra.webp', color: '#ff4500', rarity: '⭐⭐⭐' },
    { name: 'ESPRESSONA SIGNORA', emoji: '☕', description: 'Espresso-dame', image: 'images/85_espressona_signora.webp', color: '#8b4513', rarity: '⭐⭐⭐' },
    { name: 'SPAGHETTI TUALETTI', emoji: '🍝', description: 'Spaghetti-toilet', image: 'images/86_spaghetti_tualetti.png', color: '#ffd700', rarity: '⭐⭐⭐' },
    { name: 'CAPPUCCINO BABOOINO', emoji: '🐒', description: 'Kaffe-bavian', image: 'images/87_cappuccino_babooino.png', color: '#8b4513', rarity: '⭐⭐⭐' },
    { name: 'IL CACTO HIPOPOTAMO', emoji: '🦛', description: 'Kaktus-flodhest', image: 'images/il-cacto-hipopotamo.jpg.jpeg', color: '#228b22', rarity: '⭐⭐⭐' },
    { name: 'SVININO BOMBONDINO', emoji: '🐷', description: 'Bombe-gris', image: 'images/63_svinino_bombondino.jpg', color: '#ffb6c1', rarity: '⭐⭐⭐' },
    { name: 'ZIBRA ZUBRA ZIBRALINI', emoji: '🦓', description: 'Zebra-trio', image: 'images/zibra-zubra-zibralini.jpg.jpeg', color: '#000000', rarity: '⭐⭐⭐' },
    { name: 'TRACOTUCOTULU DELAPELADUSTUZ', emoji: '👽', description: 'Mystisk alien', image: 'images/tracotucotulu-delapeladustuz.jpg.jpeg', color: '#9400d3', rarity: '⭐⭐⭐⭐' },
    { name: 'TRIC TRAC BARABUM', emoji: '🥁', description: 'Trommeslager', image: 'images/tric-trac-baraboom.jpg.jpeg', color: '#ff4500', rarity: '⭐⭐⭐' },
    { name: 'GIRAFA CELESTE', emoji: '🦒', description: 'Himmelblå giraf', image: 'images/girafa-celeste.jpg.jpeg', color: '#87ceeb', rarity: '⭐⭐⭐' },
    { name: 'GIRAFFA MELONIERA', emoji: '🍈', description: 'Melon-giraf', image: 'images/117_giraffa_meloniera.png', color: '#98fb98', rarity: '⭐⭐⭐' },
    { name: 'BALLERINO LOLOLO', emoji: '💃', description: 'Dansende mand', image: 'images/ballerino-lololo.jpg.jpeg', color: '#ff69b4', rarity: '⭐⭐⭐' },
    { name: 'SPIJUNIRO GOLUBIRO', emoji: '🕊️', description: 'Spion-due', image: 'images/spijuniro-golubiro.jpg.jpeg', color: '#4682b4', rarity: '⭐⭐⭐' },
    { name: 'BULBITO BANDITO', emoji: '💡', description: 'Pære-bandit', image: 'images/36_bulbito_bandito.png', color: '#ffd700', rarity: '⭐⭐⭐' },
    { name: 'TALPA DI FERRO', emoji: '🔧', description: 'Jern-muldvarp', image: 'images/talpa-di-ferro.webp', color: '#708090', rarity: '⭐⭐⭐' },
    { name: 'SALAMINO PENGUINO', emoji: '🐧', description: 'Salami-pingvin', image: 'images/salamino-pinguino.webp', color: '#000080', rarity: '⭐⭐⭐' },
    { name: 'COCOSSINI MAMA', emoji: '🥥', description: 'Kokosnød-mor', image: 'images/90_cocossini_mama.jpg', color: '#8b4513', rarity: '⭐⭐⭐' },
    { name: 'IL PICCIONE MUSCULONE', emoji: '🐦', description: 'Muskuløs due', image: 'images/92_il_piccione_musculone.jpg', color: '#808080', rarity: '⭐⭐⭐' },
    { name: 'GRANCHIELLO SPIRITELLO', emoji: '👻', description: 'Spøgelses-krabbe', image: 'images/granchiello-spiritello.webp', color: '#f0f0f0', rarity: '⭐⭐⭐' },
    { name: 'PAPERO ASPIRATORINO', emoji: '🦆', description: 'Støvsuger-and', image: 'images/papero-aspiratorino.webp', color: '#ffd700', rarity: '⭐⭐⭐' },
    { name: 'ELEFANTINO FRIGORIFERO', emoji: '❄️', description: 'Køleskabs-elefant', image: 'images/elefantino-frigorifero.webp', color: '#add8e6', rarity: '⭐⭐⭐' },
    { name: 'HIPOPOTAMINO SUPERMARKETINO', emoji: '🛒', description: 'Supermarkeds-flodhest', image: 'images/hipopotamino-supermarketino.png', color: '#ff6347', rarity: '⭐⭐⭐' },
    { name: 'CIUF CIUF TRENO PERVITITO', emoji: '🚂', description: 'Perverteret tog', image: 'images/ciuf-ciuf-treno-pervitito.webp', color: '#4682b4', rarity: '⭐⭐⭐' },
    { name: 'RASPBERRINI RABBITINI', emoji: '🐰', description: 'Hindbær-kanin', image: 'images/raspberrini-rabbitini.webp', color: '#ff69b4', rarity: '⭐⭐⭐' },
    { name: 'PEACHI FOXILINI', emoji: '🦊', description: 'Fersken-ræv', image: 'images/peachi-foxilini.jpg.jpeg', color: '#ff8c00', rarity: '⭐⭐⭐' },
    { name: 'TIRILIKALIKA TIRILIKALAKO', emoji: '🎵', description: 'Musikalsk væsen', image: 'images/tirilikalika-tirilikalako.webp', color: '#9370db', rarity: '⭐⭐⭐' },
    { name: 'GINGOBALO GINGOBALI', emoji: '🫚', description: 'Ingefær-væsen', image: 'images/gingobalo-gingobali.webp', color: '#daa520', rarity: '⭐⭐⭐' },
    { name: 'PUSSINI SUSHINI', emoji: '🍣', description: 'Sushi-kat', image: 'images/pussini-sushini.webp', color: '#ff6347', rarity: '⭐⭐⭐' },
    { name: 'CATINI STRAWBERINI', emoji: '🍓', description: 'Jordbær-kat', image: 'images/catini-strawberini.webp', color: '#ff4500', rarity: '⭐⭐⭐' },
    { name: 'SNOOFFI ZEFFIRULLI', emoji: '🐕', description: 'Sød hund', image: 'images/89_snooffi_zeffirulli.webp', color: '#deb887', rarity: '⭐⭐⭐' },
    { name: 'BRRI BRRI BICUS DICUS', emoji: '🥶', description: 'Kold dansen', image: 'images/brri-brri-bicus-dicus-bombicus.jpg.jpeg', color: '#00bfff', rarity: '⭐⭐⭐' },
    { name: 'U DIN DIN DIN DIN DUN', emoji: '🔔', description: 'Klokke-væsen', image: 'images/u-din-din-din-din-dun-ma-din-din-din-dun.jpg.jpeg', color: '#ffd700', rarity: '⭐⭐⭐' },
    { name: 'TOB TOBI TOB TOB TOBI TOB', emoji: '🎺', description: 'Trompet-væsen', image: 'images/tob-tobi-tob-tob-tobi-tob.jpg.jpeg', color: '#ffd700', rarity: '⭐⭐⭐' },
    { name: 'LOS TRALALERITOS', emoji: '🦈', description: 'Baby-hajer', image: 'images/los-tralaleritos.jpg.jpeg', color: '#1e90ff', rarity: '⭐⭐⭐' },
    { name: 'LOS MATTEOS', emoji: '👥', description: 'Matteo-gruppen', image: 'images/matteooooooooooooo.jpg.jpeg', color: '#4169e1', rarity: '⭐⭐⭐' },
    { name: 'GARAMA AND MADUNGDUNG', emoji: '🎭', description: 'Duo-væsner', image: 'images/garamararamararaman-dan-madudungdung-tak-tuntung-perkuntung.jpg.jpeg', color: '#9932cc', rarity: '⭐⭐⭐⭐' },
    
    // === NYE FRA BEST PIC ===
    { name: 'A A A A A A A A A A SAHUR', emoji: '😱', description: 'Skrigende sahur', image: 'images/a-a-a-a-a-a-a-a-a-a-sahur.webp', color: '#ff0000', rarity: '⭐⭐' },
    { name: 'AGARRINI LA PALINI', emoji: '🌴', description: 'Palme-væsen', image: 'images/agarrini-la-palini.png', color: '#228b22', rarity: '⭐⭐⭐' },
    { name: 'ALAMAK SENIN SEKOLAH', emoji: '📚', description: 'Skole-væsen', image: 'images/alamak-senin-sekolah.webp', color: '#4169e1', rarity: '⭐⭐⭐' },
    { name: 'ALESSIO', emoji: '👦', description: 'Italiensk dreng', image: 'images/alessio.jpg.jpeg', color: '#ff6347', rarity: '⭐⭐⭐' },
    { name: 'ANTONIO', emoji: '👨', description: 'Italiensk mand', image: 'images/antonio.png', color: '#228b22', rarity: '⭐⭐⭐' },
    { name: 'API PIPI PI', emoji: '🐝', description: 'Bi-væsen', image: 'images/api-pipi-pi.webp', color: '#ffd700', rarity: '⭐⭐⭐' },
    { name: 'BALLERINA COCOCOLINA', emoji: '🥥', description: 'Kokosnød-ballerina', image: 'images/ballerina-cococolina.webp', color: '#8b4513', rarity: '⭐⭐⭐' },
    { name: 'BAMBINI CROSTINI', emoji: '🥖', description: 'Brød-børn', image: 'images/bambini-crostini.jpg.jpeg', color: '#deb887', rarity: '⭐⭐⭐' },
    { name: 'BOBRELLI BANANELLI', emoji: '🦫', description: 'Banan-bæver', image: 'images/bobrelli-bananelli.jpg.jpeg', color: '#ffd700', rarity: '⭐⭐⭐' },
    { name: 'BOBRINNI KOKOKOSINNI', emoji: '🥥', description: 'Kokosnød-bæver', image: 'images/bobrinni-kokokosinni.webp', color: '#8b4513', rarity: '⭐⭐⭐' },
    { name: 'BOMBARDINI TORTINI', emoji: '🐢', description: 'Bombe-skildpadde', image: 'images/bombardini-tortini.webp', color: '#228b22', rarity: '⭐⭐⭐' },
    { name: 'BOMBOCLAT CROCOCLAT', emoji: '🍫', description: 'Chokolade-krokodille', image: 'images/bomboclat-crococlat.webp', color: '#8b4513', rarity: '⭐⭐⭐' },
    { name: 'BRR POTATO NA POTATE', emoji: '🥔', description: 'Kold kartoffel', image: 'images/brr-potato-na-potate.webp', color: '#deb887', rarity: '⭐⭐⭐' },
    { name: 'BUDI DI DUNE', emoji: '🏜️', description: 'Ørken-væsen', image: 'images/budi-di-dune.jpg.jpeg', color: '#daa520', rarity: '⭐⭐⭐' },
    { name: 'BULLICCINNI BANANINI', emoji: '🐂', description: 'Banan-tyr', image: 'images/bulliccinni-bananini.jpg.jpeg', color: '#8b0000', rarity: '⭐⭐⭐' },
    { name: 'CAPPUCCINA MODELINA', emoji: '💃', description: 'Model-kaffe', image: 'images/cappuccina-modelina.webp', color: '#d2691e', rarity: '⭐⭐⭐' },
    { name: 'CARLOO', emoji: '🚗', description: 'Bil-væsen', image: 'images/carloo.jpg.jpeg', color: '#ff0000', rarity: '⭐⭐⭐' },
    { name: 'CEK CEK 123 SAHUR', emoji: '🎤', description: 'Mikrofon-sahur', image: 'images/cek-cek-123-sahur-ur-ur.webp', color: '#4169e1', rarity: '⭐⭐' },
    { name: 'CHACHECHICHACHACHACHI', emoji: '💃', description: 'Cha-cha danser', image: 'images/chachechichachachachi.webp', color: '#ff69b4', rarity: '⭐⭐⭐' },
    { name: 'CHICLETEIRA BICICLETEIRA', emoji: '🚲', description: 'Cykel-tyggegummi', image: 'images/chicleteira-bicicleteira.jpg.jpeg', color: '#ff69b4', rarity: '⭐⭐⭐' },
    { name: 'CHIMPANZINI WATERMELONINI KINGINI', emoji: '👑', description: 'Vandmelon-abe-konge', image: 'images/chimpanzini-watermelonini-kingini.webp', color: '#ffd700', rarity: '⭐⭐⭐⭐' },
    { name: 'CROCODILDO PENISINI', emoji: '🐊', description: 'Uartig krokodille', image: 'images/crocodildo-penisini.jpg.jpeg', color: '#228b22', rarity: '⭐⭐⭐' },
    { name: 'CROCODILLO ANANASINNO', emoji: '🍍', description: 'Ananas-krokodille', image: 'images/crocodillo-ananasinno.jpg.jpeg', color: '#ffd700', rarity: '⭐⭐⭐' },
    { name: 'DAL DAL DAL DAL SENDAL RUDAL', emoji: '🚀', description: 'Raket-sandal', image: 'images/dal-dal-dal-dal-sendal-rudal.jpg.jpeg', color: '#ff4500', rarity: '⭐⭐⭐' },
    { name: 'ECCO CAVALLO VIRTUOSO', emoji: '🐴', description: 'Virtuos hest', image: 'images/ecco-cavallo-virtuoso.jpg.jpeg', color: '#8b4513', rarity: '⭐⭐⭐' },
    { name: 'ELEFANTUCCI BANANUCCI', emoji: '🐘', description: 'Banan-elefant', image: 'images/elefantucci-bananucci.webp', color: '#808080', rarity: '⭐⭐⭐' },
    { name: 'FAFIFUFUFUFAFA', emoji: '🎵', description: 'Musikalsk nonsens', image: 'images/fafifufufufafa.webp', color: '#9370db', rarity: '⭐⭐⭐' },
    { name: 'FRANCESCO', emoji: '👨', description: 'Italiensk mand', image: 'images/francesco.png', color: '#4169e1', rarity: '⭐⭐⭐' },
    { name: 'FROGGINO FRULLATORINO', emoji: '🐸', description: 'Blender-frø', image: 'images/froggino-frullatorino.webp', color: '#228b22', rarity: '⭐⭐⭐' },
    { name: 'FRUTTA CERITA', emoji: '🍎', description: 'Frugt-historie', image: 'images/frutta-cerita.webp', color: '#ff0000', rarity: '⭐⭐⭐' },
    { name: 'GORILLINI BANANINI', emoji: '🦍', description: 'Banan-gorilla', image: 'images/gorillini-bananini.jpg.jpeg', color: '#000000', rarity: '⭐⭐⭐' },
    { name: 'GRENG GRENG BUS IRENG', emoji: '🚌', description: 'Sort bus', image: 'images/greng-greng-bus-ireng.webp', color: '#000000', rarity: '⭐⭐⭐' },
    { name: 'ICHARINNA MATCHANOVA', emoji: '🍵', description: 'Matcha-pige', image: 'images/icharinna-matchanova.webp', color: '#228b22', rarity: '⭐⭐⭐' },
    { name: 'IKAN HIU MELAYANG LAYANG', emoji: '🦈', description: 'Flyvende haj', image: 'images/ikan-hiu-melayang-layang.webp', color: '#1e90ff', rarity: '⭐⭐⭐' },
    { name: 'IL BISONTE GIUPPITERE', emoji: '🦬', description: 'Jupiter-bison', image: 'images/il-bisonte-giuppitere-giuppitercito.webp', color: '#8b4513', rarity: '⭐⭐⭐⭐' },
    { name: 'IL MASTODONTICO TELEPIEDONE', emoji: '🦣', description: 'Mammut-telefon', image: 'images/il-mastodontico-telepiedone-planetario.webp', color: '#8b4513', rarity: '⭐⭐⭐⭐' },
    { name: 'KARKIRKURKARKARKARKURKURKUR', emoji: '🦆', description: 'Kvækkende væsen', image: 'images/karkirkurkarkarkarkurkurkur.webp', color: '#ffd700', rarity: '⭐⭐⭐' },
    { name: 'KETUPAT KEPAT PREKUPAT', emoji: '🍚', description: 'Ris-væsen', image: 'images/ketupat-kepat-prekupat.webp', color: '#228b22', rarity: '⭐⭐⭐' },
    { name: 'LA ESOK SIKOLA', emoji: '🏫', description: 'Skole-væsen', image: 'images/la-esok-sikola.jpg.jpeg', color: '#4169e1', rarity: '⭐⭐⭐' },
    { name: 'LEOPARDUCCI GRAPEFRUITUCCI', emoji: '🐆', description: 'Grapefrugt-leopard', image: 'images/leoparducci-grapefruitucci.webp', color: '#ffa500', rarity: '⭐⭐⭐' },
    { name: 'MA MAU KINDER JOY', emoji: '🥚', description: 'Kinder-æg', image: 'images/ma-mau-kinder-joy.webp', color: '#ff8c00', rarity: '⭐⭐⭐' },
    { name: 'MAKAKINI BANANINI', emoji: '🐒', description: 'Banan-makak', image: 'images/makakini-bananini.jpg.jpeg', color: '#8b4513', rarity: '⭐⭐⭐' },
    { name: 'NOOO MY HOTSPOT', emoji: '📶', description: 'Mistet WiFi', image: 'images/nooo-my-hotspot.webp', color: '#ff0000', rarity: '⭐⭐⭐' },
    { name: 'OPO WAE TAKTABRAK', emoji: '💥', description: 'Kollisions-væsen', image: 'images/opo-wae-taktabrak.webp', color: '#ff4500', rarity: '⭐⭐⭐' },
    { name: 'PAKRAHMATMAMAT', emoji: '🙏', description: 'Velsignelses-væsen', image: 'images/pakrahmatmamat.jpg.jpeg', color: '#ffd700', rarity: '⭐⭐⭐' },
    { name: 'PENGUINO COCOSINO', emoji: '🐧', description: 'Kokosnød-pingvin', image: 'images/penguino-cocosino.jpg.jpeg', color: '#000000', rarity: '⭐⭐⭐' },
    { name: 'PORCOSPINO ARROSTICINO', emoji: '🦔', description: 'Grillspyd-pindsvin', image: 'images/porcospino-arrosticino.jpg.jpeg', color: '#8b4513', rarity: '⭐⭐⭐' },
    { name: 'QUESADILLA CROCODILA', emoji: '🌮', description: 'Quesadilla-krokodille', image: 'images/quesadilla-crocodila.webp', color: '#ffd700', rarity: '⭐⭐⭐' },
    { name: 'SANTI CLAUSI SPAGHETTI SAUCI', emoji: '🎅', description: 'Julemands-spaghetti', image: 'images/santi-clausi-spaghetti-sauci.webp', color: '#ff0000', rarity: '⭐⭐⭐⭐' },
    { name: 'SHTEKERITO EL BULBONITO', emoji: '💡', description: 'Pære-bandit', image: 'images/shtekerito-el-bulbonito.png', color: '#ffd700', rarity: '⭐⭐⭐' },
    { name: 'TANG TANG TANG KELENTANG', emoji: '🔔', description: 'Klokke-lyd', image: 'images/tang-tang-tang-tang-tang-tang-kelentang.png', color: '#ffd700', rarity: '⭐⭐⭐' },
    { name: 'TRENOSTRUZZO TURBO 4000', emoji: '🚄', description: 'Turbo-tog-struds', image: 'images/trenostruzzo-turbo-4000.webp', color: '#4682b4', rarity: '⭐⭐⭐' },
    { name: 'WIR WIR KIWIR ICIKIWIR', emoji: '🥝', description: 'Kiwi-væsen', image: 'images/wir-wir-kiwir-icikiwir.webp', color: '#228b22', rarity: '⭐⭐⭐' },
    { name: 'ZIP ZIP ZIP ZIP ZIP ZIP ZIP ZIP', emoji: '⚡', description: 'Lynhurtig væsen', image: 'images/zip-zip-zip-zip-zip-zip-zip-zip.webp', color: '#ffd700', rarity: '⭐⭐⭐' },
];

// Tilføj letter property automatisk baseret på første bogstav i navnet
const processedCharacters = CHARACTERS.map(char => ({
    ...char,
    letter: char.name.charAt(0).toUpperCase()
}));

// Eksporter til window for brug i spillet
window.italianBrainrotCharacters = processedCharacters;

// Node.js eksport (til test)
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { CHARACTERS: processedCharacters };
}
