// Italian Brainrot Character Descriptions - Batch 2
const BATCH_2_DESCRIPTIONS = {
"BOMBOMBINI GUSINI": {
  en: `Behold the majestic BOMBOMBINI GUSINI, the most feared and revered creature in the Italian Brainrot universe! Hatched from a forgotten military experiment involving a goose and a crate of vintage Italian fireworks, this explosive fowl is a sight to behold. With a mischievous glint in its eye and a waddle that spells impending doom, Bombombini Gusini patrols the skies, dropping 'egg-splosive' surprises on unsuspecting villagers. Its personality is a mix of a grumpy old nonno and a pyromaniac toddler. It communicates in a series of honks that strangely sound like Italian opera arias, particularly "Nessun Dorma" before a big bombing run. Special powers include laying bomb-eggs that can be customized from glitter bombs to full-on marinara sauce explosions. A funny fact? It's terrified of breadcrumbs, a tactical weakness exploited by its arch-nemesis, Bobrito Bandito.`,
  de: `Erblicken Sie die majestätische BOMBOMBINI GUSINI, die am meisten gefürchtete und verehrteste Kreatur im italienischen Brainrot-Universum! Dieses explosive Geflügel ist aus einem vergessenen Militärexperiment mit einer Gans und einer Kiste italienischer Vintage-Feuerwerkskörper entstanden. Seine Persönlichkeit ist eine Mischung aus einem mürrischen alten Nonno und einem pyromanischen Kleinkind. Es kommuniziert in einer Reihe von Hupen, die seltsamerweise wie italienische Opernarien klingen. Zu den besonderen Kräften gehört das Legen von Bombeneiern. Eine lustige Tatsache? Es hat schreckliche Angst vor Brotkrumen!`,
  es: `¡Contempla al majestuoso BOMBOMBINI GUSINI, la criatura más temida y venerada del universo italiano Brainrot! Nacida de un experimento militar olvidado que involucró un ganso y una caja de fuegos artificiales italianos antiguos, esta ave explosiva es un espectáculo digno de contemplar. Su personalidad es una mezcla de un viejo gruñón y un niño pirómano. Se comunica mediante una serie de bocinazos que extrañamente suenan a arias de ópera italiana. ¿Un dato curioso? ¡Le aterrorizan las migajas de pan!`,
  da: `Se den majestætiske BOMBOMBINI GUSINI, det mest frygtede og ærede væsen i det italienske Brainrot-univers! Udklækket fra et glemt militæreksperiment, der involverer en gås og en kasse med gammeldags italiensk fyrværkeri, er denne eksplosive fugl et syn at se. Dens personlighed er en blanding af en gnaven gammel nonno og et pyromanisk lille barn. Den kommunikerer i en række tuden, der mærkeligt nok lyder som italienske opera-arier. Et sjovt faktum? Den er bange for brødkrummer!`,
  it: `Ecco il maestoso BOMBOMBINI GUSINI, la creatura più temuta e venerata nell'universo italiano di Brainrot! Nato da un esperimento militare dimenticato che coinvolgeva un'oca e una cassa di fuochi d'artificio italiani vintage, questo uccello esplosivo è uno spettacolo da vedere. La sua personalità è un mix tra un vecchio nonno scontroso e un bambino piromane. Comunica con una serie di colpi di clacson che stranamente suonano come arie d'opera italiane. Un fatto divertente? È terrorizzato dalle briciole di pane!`,
},
"BOBRITO BANDITO": {
  en: `From the dusty plains of the Spaghetti Western dimension comes BOBRITO BANDITO, the most notorious outlaw in the Italian Brainrot world. This beaver bandit, with a tiny sombrero perched on his head and a toothpick clenched in his teeth, is wanted in three cantons for dam-building without a permit and illegal log-rustling. Bobrito is a smooth operator, a charming rogue with a heart of gold, but a very quick tail-slap for anyone who double-crosses him. His special ability is 'The Beaver Dam Diversion,' where he can instantly build a dam to flood his enemies or create a quick getaway. He's also a master of disguise, often hiding in plain sight as a rustic wooden chair. A little-known fact about Bobrito is that he has a secret passion for artisanal cheese.`,
  de: `Aus den staubigen Ebenen der Spaghetti-Western-Dimension kommt BOBRITO BANDITO, der berüchtigtste Gesetzlose in der italienischen Brainrot-Welt. Dieser Biberbandit, mit einem winzigen Sombrero auf dem Kopf und einem Zahnstocher zwischen den Zähnen, wird in drei Kantonen wegen Dammbau ohne Bewilligung gesucht. Seine besondere Fähigkeit ist „The Beaver Dam Diversion". Eine wenig bekannte Tatsache über Bobrito ist, dass er eine heimliche Leidenschaft für handwerklich hergestellten Käse hat.`,
  es: `De las polvorientas llanuras de la dimensión Spaghetti Western llega BOBRITO BANDITO, el forajido más famoso del mundo italiano Brainrot. Este castor bandido, con un diminuto sombrero en la cabeza y un palillo entre los dientes, es buscado en tres cantones por construcción de represas sin permiso. Su habilidad especial es 'The Beaver Dam Diversion'. Un hecho poco conocido sobre Bobrito es que tiene una pasión secreta por el queso artesanal.`,
  da: `Fra de støvede sletter i den vestlige spaghetti-dimension kommer BOBRITO BANDITO, den mest berygtede fredløs i den italienske Brainrot-verden. Denne bæverbandit, med en lillebitte sombrero på hovedet og en tandstikker sammenbidt i tænderne, er eftersøgt i tre kantoner for dæmningsbygning uden tilladelse. Hans særlige evne er 'The Beaver Dam Diversion'. En lidet kendt kendsgerning om Bobrito er, at han har en hemmelig passion for håndværksost.`,
  it: `Dalle polverose pianure della dimensione Spaghetti Western arriva BOBRITO BANDITO, il fuorilegge più famigerato del mondo italiano Brainrot. Questo bandito castoro, con un minuscolo sombrero in testa e uno stecchino stretto tra i denti, è ricercato in tre cantoni per costruzione di dighe senza permesso. La sua abilità speciale è "La diga del castoro". Un fatto poco noto di Bobrito è che ha una passione segreta per il formaggio artigianale.`,
},
"FRIGO CAMELO": {
  en: `Lost in the scorching deserts of Absurdistan, you might just stumble upon the oasis of refreshment that is FRIGO CAMELO. This bizarre creature is a fusion of a camel and a vintage 1950s refrigerator, born from a sandstorm that swept through a retro appliance convention. Frigo Camelo wanders the dunes, its humps replaced by a fully functional fridge and freezer, offering chilled beverages to weary travelers. Its personality is cool, calm, and collected, always ready with a cold drink and a cryptic piece of advice. Its special power, 'The Oasis Mirage,' can create a shimmering illusion of a lush paradise. Fun fact: Frigo Camelo's freezer compartment is a portal to a pocket dimension filled with infinite gelato.`,
  de: `Verloren in den sengenden Wüsten Absurdistans stoßen Sie vielleicht auf die Oase der Erfrischung, die FRIGO CAMELO ist. Dieses bizarre Geschöpf ist eine Mischung aus einem Kamel und einem Vintage-Kühlschrank aus den 1950er-Jahren. Seine besondere Kraft, „The Oasis Mirage", kann eine schimmernde Illusion eines üppigen Paradieses erschaffen. Unterhaltsame Tatsache: Das Gefrierfach von Frigo Camelo ist ein Portal zu einer Taschendimension, die mit unendlich viel Gelato gefüllt ist.`,
  es: `Perdido en los abrasadores desiertos del Absurdistán, es posible que te topes con el oasis de refrigerio que es FRIGO CAMELO. Esta extraña criatura es una fusión de un camello y un refrigerador antiguo de los años 50. Su poder especial, 'The Oasis Mirage', puede crear una ilusión brillante de un paraíso exuberante. Dato curioso: el congelador de Frigo Camelo es un portal a una dimensión de bolsillo llena de helado infinito.`,
  da: `Fortabt i Absurdistans brændende ørkener falder du måske bare over oase af forfriskning, FRIGO CAMELO. Dette bizarre væsen er en fusion af en kamel og et vintage køleskab fra 1950'erne. Dens særlige kraft, 'The Oasis Mirage', kan skabe en glitrende illusion af et frodigt paradis. Fun fact: Frigo Camelos fryserum er en portal til en lommedimension fyldt med uendelig gelato.`,
  it: `Perso negli infuocati deserti dell'Absurdistan, potresti imbatterti nell'oasi di ristoro che è FRIGO CAMELO. Questa bizzarra creatura è una fusione tra un cammello e un frigorifero vintage degli anni '50. Il suo potere speciale, "The Oasis Mirage", può creare l'illusione scintillante di un paradiso lussureggiante. Curiosità: il congelatore di Frigo Camelo è un portale per una dimensione tascabile piena di gelato infinito.`,
},
"LA VACA SATURNO SATURNITA": {
  en: `From the swirling cosmic dust of the Milky Way gallops LA VACA SATURNO SATURNITA, the celestial bovine from the rings of Saturn. This space cow, with a coat that shimmers with the light of a thousand stars and planetary rings that orbit its body, is a truly stellar sight. La Vaca Saturno Saturnita is a gentle and wise creature, a cosmic mother figure to all the lost socks and forgotten dreams that float in space. She communicates through a series of moos that resonate with the music of the spheres. Her special ability, 'The Milky Way Wave,' can create a wave of cosmic milk that can heal any wound. A funny fact about this cosmic cow is that she produces the best cheese in the galaxy, a delicacy known as 'Saturn-zarella.'`,
  de: `Aus dem wirbelnden kosmischen Staub der Milchstraße galoppiert LA VACA SATURNO SATURNITA, das himmlische Rind aus den Ringen des Saturn. Diese Weltraumkuh mit einem Fell, das im Licht tausender Sterne schimmert, ist ein wahrhaft stellarer Anblick. Ihre Spezialfähigkeit „Die Milchstraßenwelle" kann eine Welle kosmischer Milch erzeugen, die jede Wunde heilen kann. Eine lustige Tatsache: Sie produziert den besten Käse der Galaxie, eine Delikatesse namens „Saturn-Zarella".`,
  es: `Del arremolinado polvo cósmico de la Vía Láctea galopa LA VACA SATURNO SATURNITA, el bovino celeste de los anillos de Saturno. Esta vaca espacial, con un pelaje que brilla con la luz de mil estrellas, es una vista verdaderamente estelar. Su habilidad especial, 'La Ola de la Vía Láctea', puede crear una ola de leche cósmica que puede curar cualquier herida. Un dato curioso: produce el mejor queso de la galaxia, un manjar conocido como 'Saturn-zarella'.`,
  da: `Fra Mælkevejens hvirvlende kosmiske støv galopperer LA VACA SATURNO SATURNITA, det himmelske kvæg fra Saturns ringe. Denne rumko, med en pels, der skinner af lyset fra tusind stjerner, er et virkelig stjernesyn. Hendes særlige evne, 'Mælkevejsbølgen', kan skabe en bølge af kosmisk mælk, der kan hele ethvert sår. En sjov kendsgerning: hun producerer den bedste ost i galaksen, en delikatesse kendt som 'Saturn-zarella'.`,
  it: `Dalle vorticose polveri cosmiche della Via Lattea galoppa LA VACA SATURNO SATURNITA, il bovino celeste proveniente dagli anelli di Saturno. Questa mucca spaziale, con il mantello che brilla della luce di mille stelle, è uno spettacolo davvero stellare. La sua abilità speciale, "L'onda della Via Lattea", può creare un'onda di latte cosmico in grado di curare qualsiasi ferita. Una cosa divertente: produce il miglior formaggio della galassia, una prelibatezza conosciuta come "Saturn-zarella".`,
},
"TRULIMERO TRULICINA": {
  en: `In the whimsical land of Italian Brainrot, where the absurd is the everyday, resides the enigmatic TRULIMERO TRULICINA. This creature is a living paradox, a being with two distinct personalities housed in a single, bizarre body. One side, Trulimero, is a cheerful, optimistic fellow who sees the world through rose-tinted glasses. The other side, Trulicina, is a cynical, grumpy character who expects the worst at every turn. They are in a constant state of bickering and philosophical debate. Their special power is 'The Duality Dance,' a chaotic whirlwind of conflicting actions that somehow always manages to save the day. Fun fact: Trulimero and Trulicina can never agree on what to have for dinner, so they survive on a diet of half-and-half pizzas.`,
  de: `Im skurrilen Land des italienischen Brainrot lebt der rätselhafte TRULIMERO TRULICINA. Diese Kreatur ist ein lebendes Paradoxon, ein Wesen mit zwei unterschiedlichen Persönlichkeiten in einem einzigen, bizarren Körper. Ihre besondere Kraft ist „The Duality Dance". Unterhaltsame Tatsache: Trulimero und Trulicina können sich nie darauf einigen, was sie zu Abend essen sollen, also überleben sie mit einer Diät aus halb und halb Pizzen.`,
  es: `En la caprichosa tierra del Brainrot italiano reside el enigmático TRULIMERO TRULICINA. Esta criatura es una paradoja viviente, un ser con dos personalidades distintas alojadas en un único y extraño cuerpo. Su poder especial es 'La Danza de la Dualidad'. Dato curioso: Trulimero y Trulicina nunca se ponen de acuerdo sobre qué cenar, por lo que sobreviven con una dieta de mitades de pizzas.`,
  da: `I det finurlige land italienske Brainrot bor den gådefulde TRULIMERO TRULICINA. Dette væsen er et levende paradoks, et væsen med to adskilte personligheder i en enkelt, bizar krop. Deres særlige kraft er 'The Duality Dance'. Fun fact: Trulimero og Trulicina kan aldrig blive enige om, hvad de skal have til aftensmad, så de overlever på en diæt med halve og halve pizzaer.`,
  it: `Nella stravagante terra di Italian Brainrot risiede l'enigmatico TRULIMERO TRULICINA. Questa creatura è un paradosso vivente, un essere con due personalità distinte racchiuse in un unico, bizzarro corpo. Il loro potere speciale è "La Danza della Dualità". Curiosità: Trulimero e Trulicina non riescono mai a mettersi d'accordo su cosa mangiare per cena, quindi sopravvivono con una dieta metà e metà pizza.`,
},
"BURBALONI LULILOLI": {
  en: `Floating gently on the zephyrs of the Italian Brainrot world is the ethereal BURBALONI LULILOLI. This creature is a living, breathing bubble, a shimmering sphere of iridescent soap film with a giggling face. Born from a child's wish on a summer breeze, Burbaloni Luliloli is the embodiment of pure joy and innocence. It drifts through the skies, leaving a trail of smaller, giggling bubbles in its wake. Its personality is light, bubbly, and carefree. Its special power, 'The Bubble Barrier,' can create an impenetrable shield of bubbles. A funny fact about Burbaloni Luliloli is that it can't stop hiccupping, and every hiccup releases a shower of rainbow-colored confetti.`,
  de: `Sanft auf den Winden der italienischen Brainrot-Welt schwebt der ätherische BURBALONI LULILOLI. Dieses Geschöpf ist eine lebende, atmende Blase, eine schimmernde Kugel aus schillerndem Seifenfilm mit einem kichernden Gesicht. Seine besondere Kraft, die „Blasenbarriere", kann einen undurchdringlichen Schutzschild aus Blasen erschaffen. Eine lustige Tatsache: es kann nicht aufhören zu schlucken und jeder Schluckauf löst einen Regen regenbogenfarbenen Konfetti aus.`,
  es: `Flotando suavemente sobre los céfiros del mundo italiano Brainrot está el etéreo BURBALONI LULILOLI. Esta criatura es una burbuja viva que respira, una esfera reluciente de película de jabón iridiscente con una cara risueña. Su poder especial, 'La Barrera de Burbujas', puede crear un escudo impenetrable de burbujas. Un dato curioso: no puede dejar de tener hipo, y cada hipo libera una lluvia de confeti de colores del arco iris.`,
  da: `Den æteriske BURBALONI LULILOLI flyder blidt på zephyrerne i den italienske Brainrot-verden. Dette væsen er en levende, åndende boble, en glitrende kugle af iriserende sæbefilm med et fnisende ansigt. Dens særlige kraft, 'The Bubble Barrier', kan skabe et uigennemtrængeligt skjold af bobler. En sjov kendsgerning: den kan ikke stoppe med at hikke, og hvert hikke udløser en byge af regnbuefarvet konfetti.`,
  it: `Galleggia dolcemente sugli zefiri del mondo italiano Brainrot l'etereo BURBALONI LULILOLI. Questa creatura è una bolla vivente e respirante, una sfera scintillante di pellicola di sapone iridescente con una faccia ridacchiante. Il suo potere speciale, "La barriera delle bolle", può creare uno scudo impenetrabile di bolle. Una cosa divertente: non riesce a smettere di singhiozzare, e ogni singhiozzo rilascia una pioggia di coriandoli color arcobaleno.`,
},
"GLORBO FRUTTODRILLO": {
  en: `Deep in the heart of the Tutti Frutti Jungle, a new king reigns: GLORBO FRUTTODRILLO. This magnificent beast is a hybrid of a gorilla and a fruit stand, its body covered in a luscious coat of ripe, juicy fruits. Glorbo is a benevolent ruler, a gentle giant who shares his fruity bounty with all the creatures of the jungle. His special power, 'The Fruit Fury,' allows him to launch a barrage of explosive fruits at his enemies. Fun fact: Glorbo's favorite pastime is juggling pineapples while singing opera.`,
  de: `Tief im Herzen des Tutti-Frutti-Dschungels regiert ein neuer König: GLORBO FRUTTODRILLO. Dieses prächtige Tier ist eine Mischung aus einem Gorilla und einem Fruchtstand. Seine besondere Kraft „Fruit Fury" ermöglicht es ihm, eine Flut explosiver Früchte auf seine Feinde abzufeuern. Unterhaltsame Tatsache: Glorbos Lieblingsbeschäftigung ist das Jonglieren mit Ananas und gleichzeitig Operngesang.`,
  es: `En lo profundo del corazón de la Selva Tutti Frutti, reina un nuevo rey: GLORBO FRUTTODRILLO. Esta magnífica bestia es un híbrido de gorila y puesto de frutas. Su poder especial, 'The Fruit Fury', le permite lanzar una andanada de frutas explosivas a sus enemigos. Dato curioso: el pasatiempo favorito de Glorbo es hacer malabarismos con piñas mientras canta ópera.`,
  da: `Dybt i hjertet af Tutti Frutti-junglen hersker en ny konge: GLORBO FRUTTODRILLO. Dette storslåede udyr er en hybrid af en gorilla og en frugtstand. Hans særlige kraft, 'The Fruit Fury', giver ham mulighed for at lancere en byge af eksplosive frugter mod sine fjender. Fun fact: Glorbos yndlingsbeskæftigelse er at jonglere med ananas, mens du synger opera.`,
  it: `Nel cuore della Tutti Frutti Jungle, regna un nuovo re: GLORBO FRUTTODRILLO. Questa magnifica bestia è un ibrido tra un gorilla e un banco di frutta. Il suo potere speciale, "The Fruit Fury", gli permette di lanciare una raffica di frutti esplosivi contro i suoi nemici. Curiosità: il passatempo preferito di Glorbo è fare il giocoliere con gli ananas mentre canta l'opera.`,
},
"FRULLI FRULLA": {
  en: `Beware the whirlwind of flavor, the tempest of taste, the one and only FRULLI FRULLA! This chaotic creature is a living tornado made of spinning fruits, a vortex of fruity fury that dances across the landscape. Born from a blender that was struck by lightning, Frulli Frulla is a force of nature. Its special power, 'The Smoothie Spin,' can suck up its enemies and blend them into a delicious smoothie. A funny fact: it gets dizzy if it spins counter-clockwise for too long.`,
  de: `Hüten Sie sich vor dem Wirbelwind des Geschmacks, dem Sturm des Geschmacks, dem einzigartigen FRULLI FRULLA! Diese chaotische Kreatur ist ein lebender Tornado aus sich drehenden Früchten. Seine besondere Kraft, „The Smoothie Spin", kann seine Feinde aufsaugen und sie zu einem köstlichen Smoothie vermischen. Eine lustige Tatsache: ihm wird schwindelig, wenn er sich zu lange gegen den Uhrzeigersinn dreht.`,
  es: `¡Cuidado con el torbellino de sabores, la tempestad de sabores, el único FRULLI FRULLA! Esta criatura caótica es un tornado viviente hecho de frutas que giran. Su poder especial, 'The Smoothie Spin', puede absorber a sus enemigos y mezclarlos en un delicioso batido. Un dato curioso: se marea si gira en el sentido contrario a las agujas del reloj durante demasiado tiempo.`,
  da: `Pas på smagens hvirvelvind, smagens storm, den eneste FRULLI FRULLA! Dette kaotiske væsen er en levende tornado lavet af spindende frugter. Dens særlige kraft, 'The Smoothie Spin', kan suge sine fjender til sig og blande dem til en lækker smoothie. En sjov kendsgerning: den bliver svimmel, hvis den drejer mod uret for længe.`,
  it: `Attenti al vortice del sapore, alla tempesta del gusto, ai soli e inimitabili FRULLI FRULLA! Questa creatura caotica è un tornado vivente fatto di frutti rotanti. Il suo potere speciale, "The Smoothie Spin", può risucchiare i suoi nemici e mescolarli in un frullato delizioso. Una cosa divertente: ha le vertigini se gira in senso antiorario per troppo tempo.`,
},
"RHINO TOASTERINO": {
  en: `From the breakfast savannas of the Italian Brainrot world comes the mighty RHINO TOASTERINO. This incredible creature is a hybrid of a rhinoceros and a toaster, with a chrome-plated hide and slots on its back for toasting bread. Rhino Toasterino is a grumpy but good-hearted creature, a breakfast guardian who ensures that everyone starts their day with a perfectly toasted slice of bread. Its special power, 'The Burnt Toast Barrage,' allows it to launch a volley of burnt, razor-sharp toast at its enemies. Fun fact: Rhino Toasterino's horn is a built-in butter dispenser.`,
  de: `Aus den Frühstückssavannen der italienischen Brainrot-Welt kommt der mächtige RHINO TOASTERINO. Dieses unglaubliche Geschöpf ist eine Mischung aus Nashorn und Toaster. Seine besondere Kraft „The Burnt Toast Barrage" ermöglicht es ihm, eine Salve verbrannter, messerscharfer Toasts auf seine Feinde abzufeuern. Wissenswertes: Die Hupe des Rhino Toasterino ist ein eingebauter Butterspender.`,
  es: `De las sabanas de desayuno del mundo italiano Brainrot llega el poderoso RHINO TOASTERINO. Esta increíble criatura es un híbrido de rinoceronte y tostadora. Su poder especial, 'The Burnt Toast Barrage', le permite lanzar una ráfaga de tostadas quemadas y afiladas contra sus enemigos. Dato curioso: el cuerno de Rhino Toasterino es un dispensador de mantequilla incorporado.`,
  da: `Fra morgenmadssavannerne i den italienske Brainrot-verden kommer det mægtige RHINO TOASTERINO. Dette utrolige væsen er en hybrid af et næsehorn og en brødrister. Dens særlige kraft, 'The Burnt Toast Barrage', gør det muligt for den at sende en salve af brændt, knivskarp toast mod sine fjender. Fun fact: Rhino Toasterinos horn er en indbygget smørdispenser.`,
  it: `Dalle savane da colazione del mondo italiano Brainrot arriva il potente RHINO TOASTERINO. Questa incredibile creatura è un ibrido tra un rinoceronte e un tostapane. Il suo potere speciale, "The Burnt Toast Barrage", gli consente di lanciare una raffica di toast bruciati e affilati come rasoi contro i suoi nemici. Curiosità: il corno di Rhino Toasterino è un distributore di burro integrato.`,
},
"ORANGUTINI ANANASINI": {
  en: `Swinging from the pineapple trees of the tropical paradise of Isola Ananas is the laid-back ORANGUTINI ANANASINI. This chill creature is a hybrid of an orangutan and a pineapple, with a spiky, golden-brown body and a leafy green hairdo. Orangutini Ananasini is the epitome of cool, a zen master who spends its days meditating and sipping on pineapple juice. Its special power, 'The Pineapple Peace,' can create a wave of calming energy that can pacify even the most ferocious of beasts. A funny fact: it can play the ukulele with its feet.`,
  de: `Von den Ananasbäumen des tropischen Paradieses Isola Ananas schwingt der entspannte ORANGUTINI ANANASINI. Dieses kühle Wesen ist eine Kreuzung aus einem Orang-Utan und einer Ananas. Seine besondere Kraft, der „Ananasfrieden", kann eine Welle beruhigender Energie erzeugen. Eine lustige Tatsache: es kann mit den Füßen Ukulele spielen.`,
  es: `Colgando de los piñas del paraíso tropical de Isola Ananas se encuentra el relajado ORANGUTINI ANANASINI. Esta fría criatura es un híbrido de orangután y piña. Su poder especial, 'La Paz de la Piña', puede crear una ola de energía calmante. Un dato curioso: puede tocar el ukelele con los pies.`,
  da: `Den tilbagelænede ORANGUTINI ANANASINI svinger sig fra ananastræerne i det tropiske paradis Isola Ananas. Dette kølige væsen er en hybrid af en orangutang og en ananas. Dens særlige kraft, 'The Pineapple Peace', kan skabe en bølge af beroligende energi. En sjov kendsgerning: den kan spille ukulele med sine fødder.`,
  it: `A dondolare tra gli alberi di ananas del paradiso tropicale di Isola Ananas c'è il rilassato ORANGUTINI ANANASINI. Questa creatura gelida è un ibrido tra un orangutan e un ananas. Il suo potere speciale, "La pace dell'ananas", può creare un'ondata di energia calmante. Una cosa divertente: sa suonare l'ukulele con i piedi.`,
},
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = BATCH_2_DESCRIPTIONS;
}
