// Italian Brainrot Character Descriptions - Batch 7
// Characters (15): GORILLINI BANANINI, GRENG GRENG BUS IRENG, ICHARINNA MATCHANOVA, IKAN HIU MELAYANG LAYANG, IL BISONTE GIUPPITERE, IL MASTODONTICO TELEPIEDONE, KARKIRKURKARKARKARKURKURKUR, KETUPAT KEPAT PREKUPAT, LA ESOK SIKOLA, LEOPARDUCCI GRAPEFRUITUCCI, MA MAU KINDER JOY, MAKAKINI BANANINI, NOOO MY HOTSPOT, OPO WAE TAKTABRAK, PAKRAHMATMAMAT
// Languages: English (en), Deutsch (de), Español (es), Dansk (da), Italiano (it)

const BATCH_7_DESCRIPTIONS = {
"GORILLINI BANANINI": {
en: `Origin: Born in the mystical banana jungles of the Italian Brainrot universe, GORILLINI BANANINI is the legendary banana-gorilla hybrid that nobody asked for but everyone secretly loves. Created after an accidental mix-up in a fruit stand and a zoo, this quirky chimera swings through the meme vines with unmatched style. Personality: GORILLINI BANANINI is absurdly chill yet absurdly hyperactive. It loves throwing banana peels as jokes and can often be found philosophizing about the meaning of life while munching on a bunch of bananas. It's part prankster, part wise guru, and all parts weirdly lovable. Special Powers/Abilities: This fruity beast can peel itself to transform into a slippery banana-shaped missile, confuse enemies with sudden banana aroma attacks, and summon a horde of tiny banana minions that dance salsa. Its mighty gorilla strength means it can crush negativity (and coconuts) with ease. Role in the Italian Brainrot universe: GORILLINI BANANINI serves as the ultimate chaos agent and meme ambassador, spreading nonsensical joy and slippery laughter across the meme-lands. It's the go-to character when things get too serious and someone needs to slip on a banana peel of irony. Funny Facts: GORILLINI BANANINI once tried to start a banana-themed boy band called "The Peelings." It has an irrational fear of smoothie blenders and a secret hobby of writing banana poetry in iambic pentapeel.`,
de: `Ursprung: Geboren im mystischen Bananendschungel des Italian Brainrot-Universums, ist GORILLINI BANANINI das legendäre Bananen-Gorilla-Hybrid, das niemand bestellt hat, aber heimlich alle lieben. Entstanden durch eine versehentliche Vermischung an einem Obststand und im Zoo schwingt dieses skurrile Chimärenwesen mit unvergleichlichem Stil durch die Meme-Lianen. Persönlichkeit: GORILLINI BANANINI ist absurd gelassen und gleichzeitig hyperaktiv. Es liebt es, Bananenschalen als Witze zu werfen und philosophiert oft über den Sinn des Lebens, während es eine Handvoll Bananen mampft. Es ist Teil Spaßvogel, Teil weiser Guru und insgesamt eigenartig liebenswert. Spezialkräfte/Fähigkeiten: Dieses fruchtige Biest kann sich schälen, um sich in eine rutschige bananenförmige Rakete zu verwandeln, Gegner mit plötzlichen Bananen-Aromaatacken verwirren und eine Horde winziger Bananenminions beschwören, die Salsa tanzen. Seine mächtige Gorilla-Stärke erlaubt es ihm, Negativität (und Kokosnüsse) mühelos zu zerquetschen. Rolle im Italian Brainrot-Universum: GORILLINI BANANINI fungiert als ultimative Chaos-Agentur und Meme-Botschafter, verbreitet unsinnige Freude und rutschiges Lachen über die Meme-Lande. Es ist der Charakter, den man ruft, wenn es zu ernst wird und jemand auf der Bananenschale der Ironie ausrutschen muss. Lustige Fakten: GORILLINI BANANINI versuchte einmal, eine bananengebundene Boyband namens „The Peelings" zu gründen. Es hat eine irrationale Angst vor Smoothie-Mixern und das geheime Hobby, Bananenpoesie im jambischen Pentapeel zu schreiben.`,
es: `Origen: Nacido en las místicas junglas de plátanos del universo Italian Brainrot, GORILLINI BANANINI es el legendario híbrido plátano-gorila que nadie pidió pero que todos secretamente adoran. Creado tras un accidente entre un puesto de frutas y un zoológico, este curioso quimera se balancea entre las lianas de memes con un estilo inigualable. Personalidad: GORILLINI BANANINI es absurdamente tranquilo pero también absurdamente hiperactivo. Le encanta lanzar cáscaras de plátano como bromas y a menudo se le encuentra filosofando sobre el sentido de la vida mientras mastica un racimo de plátanos. Es parte bromista, parte sabio gurú y completamente adorable en su rareza. Poderes especiales/Habilidades: Esta bestia frutal puede pelarse para transformarse en un misil resbaladizo con forma de plátano, confundir a los enemigos con ataques súbitos de aroma a plátano y convocar una horda de pequeños minions que bailan salsa. Su fuerza gorila le permite aplastar la negatividad (y cocos) con facilidad. Rol en el universo Italian Brainrot: GORILLINI BANANINI actúa como el agente supremo del caos y embajador de memes, esparciendo alegría absurda y risas resbaladizas por las tierras de memes. Es el personaje al que acudir cuando la cosa se pone seria y alguien necesita resbalar en la cáscara de la ironía. Datos curiosos: GORILLINI BANANINI intentó formar una boy band temática de plátanos llamada "The Peelings". Tiene un miedo irracional a las licuadoras y un pasatiempo secreto: escribir poesía bananera en pentapéel yámbico.`,
da: `Oprindelse: Født i de mystiske bananjungle i Italian Brainrot-universet, er GORILLINI BANANINI den legendariske banan-gorilla hybrid, som ingen bad om, men som alle hemmeligt elsker. Skabt efter en tilfældig sammenblanding mellem en frugtbod og en zoo, svinger denne mærkværdige chimære sig gennem memernes lianer med ubeskrivelig stil. Personlighed: GORILLINI BANANINI er absurd afslappet men også absurd hyperaktiv. Den elsker at kaste bananskræller som jokes og kan ofte findes filosofere over livets mening, mens den gnasker i en klase bananer. Den er del prankster, del vis guru og på alle måder mærkeligt elskværdig. Specielle kræfter/evner: Dette frugtede bæst kan skrelle sig selv for at forvandle sig til en glat, bananformet missil, forvirre fjender med pludselige bananduftangreb og kalde en hær af små banan-minions frem, der danser salsa. Dens mægtige gorillestyrke betyder, at den let kan knuse negativitet (og kokosnødder). Rolle i Italian Brainrot-universet: GORILLINI BANANINI fungerer som den ultimative kaosagent og meme-ambassadør, der spreder meningsløs glæde og glidende latter over meme-landene. Det er den karakter, man ringer til, når tingene bliver for seriøse, og nogen skal glide på ironiens bananskal. Sjove fakta: GORILLINI BANANINI prøvede engang at starte et banan-tema boyband kaldet "The Peelings". Den har en irrationel frygt for smoothieblendere og en hemmelig hobby med at skrive bananpoesi i jambisk pentapeel.`,
it: `Origine: Nato nelle misteriose giungle di banane dell'universo Italian Brainrot, GORILLINI BANANINI è il leggendario ibrido banana-gorilla che nessuno ha chiesto ma che tutti amano segretamente. Creato dopo un incidente tra una bancarella di frutta e uno zoo, questa strana chimera si dondola tra le liane dei meme con uno stile inimitabile. Personalità: GORILLINI BANANINI è assurdo nel suo essere rilassato ma anche iperattivo allo stesso tempo. Ama lanciare bucce di banana come scherzi e spesso lo si trova a filosofeggiare sul senso della vita mentre sgranocchia un mazzo di banane. È parte burlone, parte saggio guru, e totalmente stranamente adorabile. Poteri speciali/Abilità: Questa bestia fruttata può sbucciarsi per trasformarsi in un missile scivoloso a forma di banana, confondere i nemici con improvvisi attacchi di aroma di banana e convocare un esercito di minuscoli minion banana che ballano salsa. La sua enorme forza da gorilla gli permette di schiacciare la negatività (e le noci di cocco) con facilità. Ruolo nell'universo Italian Brainrot: GORILLINI BANANINI è l'agente del caos supremo e ambasciatore dei meme, diffondendo gioia insensata e risate scivolose nelle terre dei meme. È il personaggio a cui si ricorre quando le cose si fanno troppo serie e qualcuno deve scivolare sulla buccia d'ironia. Curiosità divertenti: GORILLINI BANANINI ha tentato di fondare una boy band a tema banana chiamata "The Peelings". Ha una paura irrazionale dei frullatori e un hobby segreto: scrivere poesie banana in pentapeel iambico.`
}
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = BATCH_7_DESCRIPTIONS;
}
