// Italian Brainrot Character Descriptions - Batch 8
// Characters (9): PENGUINO COCOSINO, PORCOSPINO ARROSTICINO, QUESADILLA CROCODILA, SANTI CLAUSI SPAGHETTI SAUCI, SHTEKERITO EL BULBONITO, TANG TANG TANG KELENTANG, TRENOSTRUZZO TURBO 4000, WIR WIR KIWIR ICIKIWIR, ZIP ZIP ZIP ZIP ZIP ZIP ZIP ZIP
// Languages: English (en), Deutsch (de), Español (es), Dansk (da), Italiano (it)

const BATCH_8_DESCRIPTIONS = {
"PENGUINO COCOSINO": {
en: `From the tropical shores of the Italian Brainrot archipelago comes PENGUINO COCOSINO, the coconut-penguin hybrid that defies all logic. Hatched from a coconut that fell into a penguin's nest during a bizarre coastal storm, this creature is a walking, waddling paradox. Its body is a perfect sphere of coconut shell, complete with three holes, from which its penguin head and flippers emerge. PENGUINO COCOSINO is a laid-back, beach-loving bird, often seen sunbathing on the sand or attempting to surf on its own coconut body. Its special power is the "Coconut Milkshake," a dizzying spin that sprays a refreshing, if slightly disorienting, mist of coconut milk. In the Italian Brainrot ecosystem, it serves as the official bartender, mixing tropical drinks for the other creatures. A funny fact: it has a deep, philosophical hatred of straws, viewing them as an existential threat to its coconut brethren.`,
de: `Von den tropischen Küsten des italienischen Brainrot-Archipels kommt PENGUINO COCOSINO, der Kokosnuss-Pinguin-Hybrid, der jeder Logik trotzt. Aus einer Kokosnuss geschlüpft, die während eines bizarren Küstensturms in das Nest eines Pinguins fiel, ist diese Kreatur ein wandelndes, watschelndes Paradoxon. Ihr Körper ist eine perfekte Kugel aus Kokosnussschale, komplett mit drei Löchern, aus denen ihr Pinguinkopf und ihre Flossen hervorkommen. PENGUINO COCOSINO ist ein entspannter, strandliebender Vogel, der oft beim Sonnenbaden im Sand oder beim Versuch, auf seinem eigenen Kokosnusskörper zu surfen, gesehen wird. Seine besondere Kraft ist der "Kokosnuss-Milchshake", eine schwindelerregende Drehung, die einen erfrischenden, wenn auch leicht desorientierenden, Nebel aus Kokosmilch versprüht. Im italienischen Brainrot-Ökosystem dient es als offizieller Barkeeper und mischt tropische Getränke für die anderen Kreaturen. Eine lustige Tatsache: Es hegt einen tiefen, philosophischen Hass auf Strohhalme und betrachtet sie als existenzielle Bedrohung für seine Kokosnuss-Brüder.`,
es: `De las costas tropicales del archipiélago de Italian Brainrot llega PENGUINO COCOSINO, el híbrido de pingüino y coco que desafía toda lógica. Nacida de un coco que cayó en el nido de un pingüino durante una extraña tormenta costera, esta criatura es una paradoja andante y que se contonea. Su cuerpo es una esfera perfecta de cáscara de coco, con tres agujeros, de los que emergen su cabeza y aletas de pingüino. PENGUINO COCOSINO es un pájaro relajado y amante de la playa, a menudo visto tomando el sol en la arena o intentando surfear en su propio cuerpo de coco. Su poder especial es el "Batido de Coco", un giro vertiginoso que rocía una niebla refrescante, aunque ligeramente desorientadora, de leche de coco. En el ecosistema de Italian Brainrot, sirve como el barman oficial, mezclando bebidas tropicales para las otras criaturas. Un dato curioso: tiene un odio profundo y filosófico por las pajitas, viéndolas como una amenaza existencial para sus hermanos cocos.`,
da: `Fra de tropiske kyster i den italienske Brainrot-øgruppe kommer PENGUINO COCOSINO, kokos-pingvin-hybriden, der trodser al logik. Udklækket fra en kokosnød, der faldt i en pingvins rede under en bizar kyststorm, er denne skabning en gående, vraltende paradoks. Kroppen er en perfekt kugle af kokosnøddeskal, komplet med tre huller, hvorfra dens pingvinhoved og luffer kommer frem. PENGUINO COCOSINO er en afslappet, strandelskende fugl, der ofte ses solbade på sandet eller forsøger at surfe på sin egen kokosnødkrop. Dens særlige kraft er "Kokos-Milkshake", et svimlende spin, der sprøjter en forfriskende, omend let desorienterende, tåge af kokosmælk. I det italienske Brainrot-økosystem fungerer den som den officielle bartender, der blander tropiske drinks til de andre skabninger. En sjov kendsgerning: den har et dybt, filosofisk had til sugerør og ser dem som en eksistentiel trussel mod sine kokosnøddebrødre.`,
it: `Dalle coste tropicali dell'arcipelago di Italian Brainrot arriva PENGUINO COCOSINO, l'ibrido pinguino-cocco che sfida ogni logica. Nato da una noce di cocco caduta nel nido di un pinguino durante una bizzarra tempesta costiera, questa creatura è un paradosso che cammina e ondeggia. Il suo corpo è una sfera perfetta di guscio di noce di cocco, completa di tre fori, da cui emergono la testa e le pinne da pinguino. PENGUINO COCOSINO è un uccello rilassato e amante della spiaggia, spesso visto prendere il sole sulla sabbia o tentare di fare surf sul proprio corpo di cocco. Il suo potere speciale è il "Frullato di Cocco", una rotazione vertiginosa che spruzza una nebbia rinfrescante, anche se leggermente disorientante, di latte di cocco. Nell'ecosistema di Italian Brainrot, funge da barista ufficiale, mescolando drink tropicali per le altre creature. Un fatto divertente: ha un odio profondo e filosofico per le cannucce, considerandole una minaccia esistenziale per i suoi fratelli cocco.`
}
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = BATCH_8_DESCRIPTIONS;
}
